#!/usr/bin/env python3
# Regenerates lib/generated/desktop_sync_script.dart from
# desktop/localsync_sync.sh - run after every edit to the script:
#   python3 tool/gen_desktop_script.py
# test/desktop_sync_script_test.dart fails if the two ever drift apart.
#
# 2026-09-24: why a Dart constant instead of a Flutter asset - App Store
# upload rejected the .ipa (ITMS-90035, "Code object is not signed at
# all") because the bundled asset desktop/localsync_sync.sh is a shell
# script ("#!" first line). Apple treats that as unsigned code even with
# its +x bit removed. As a string inside the app's compiled code there
# is no script file in the bundle at all.
from pathlib import Path

root = Path(__file__).resolve().parent.parent
script = (root / "desktop" / "localsync_sync.sh").read_text()
assert "'''" not in script, "script contains ''' - pick another delimiter"
out = root / "lib" / "generated" / "desktop_sync_script.dart"
out.write_text(
    "// GENERATED by tool/gen_desktop_script.py from desktop/localsync_sync.sh\n"
    "// - do not edit by hand; edit the .sh and re-run the tool.\n"
    "// ignore_for_file: prefer_single_quotes\n\n"
    "const kDesktopSyncScript = r'''" + script + "''';\n"
)
print(f"wrote {out.relative_to(root)} ({len(script)} chars)")
